INSERT INTO Fruit(id,name,season) VALUES (1,'Mango','Spring');
INSERT INTO Fruit(id,name,season) VALUES (2,'Strawberry','Spring');
INSERT INTO Fruit(id,name,season) VALUES (3,'Orange','Winter');
INSERT INTO Fruit(id,name,season) VALUES (4,'Lemon','Winter');
INSERT INTO Fruit(id,name,season) VALUES (5,'Blueberry','Summer');
INSERT INTO Fruit(id,name,season) VALUES (6,'Banana','Summer');
INSERT INTO Fruit(id,name,season) VALUES (7,'Watermelon','Summer');
INSERT INTO Fruit(id,name,season) VALUES (8,'Apple','Fall');
INSERT INTO Fruit(id,name,season) VALUES (9,'Pear','Fall');
INSERT INTO Fruit(id,name,season) VALUES (10,'Češnja','Pomlad');
ALTER SEQUENCE fruit_seq RESTART WITH 11;